cc_test(
    name = "unit_tests",
    srcs = [
        "condition_test.cpp",
        "dispatcher_test.cpp",
        "utils_test.cpp",
    ],
    deps = [
        "//include:lib",
        "@gtest//:gtest_main",
    ],
)
