cc_library(
    name = "lib",
    hdrs = [
        "condition.hpp",
        "dispatcher.hpp",
        "element.hpp",
        "slice.hpp",
        "utils.hpp",
    ],
    visibility = ["//visibility:public"],
)
