name: Simple checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ubuntu-and-mac:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [gcc, clang]
    name: ${{matrix.os}}:${{matrix.compiler}}
    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: |
        CC=${{matrix.compiler}} bazel build --verbose_failures //...:all

    - name: Test
      run: |
        CC=${{matrix.compiler}} bazel test //...:all
